Revert r38813: python 3.3 regression.
Reopens: #6499

{{{
Traceback (most recent call last):
  File "admin/run-python3-tests", line 30, in <module>
    unittest.main(module=None, argv=["run-python3-tests", "-v"] + testModules)
  File "/usr/lib/python3.3/unittest/main.py", line 124, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.3/unittest/main.py", line 168, in parseArgs
    self.createTests()
  File "/usr/lib/python3.3/unittest/main.py", line 175, in createTests
    self.module)
  File "/usr/lib/python3.3/unittest/loader.py", line 137, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.3/unittest/loader.py", line 137, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.3/unittest/loader.py", line 96, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/var/lib/buildbot/buildarea/python-3.3-tests/Twisted/twisted/internet/test/test_endpoints.py", line 1780, in <module>
    class ServerStringTests(unittest.TestCase):
  File "/var/lib/buildbot/buildarea/python-3.3-tests/Twisted/twisted/internet/test/test_endpoints.py", line 1845, in ServerStringTests
    % (escapedPEMPathName,))
NameError: name 'escapedPEMPathName' is not defined
}}}

git-svn-id: svn://svn.twistedmatrix.com/svn/Twisted/trunk@38817 bbbe8e31-12d6-0310-92fd-ac37d47ddeeb