Revert r40032: Merge reflect-deprecate-6689: Remove deprecated classes from twisted.python.reflect.
Failing tests because the Version import was removed mistakenly.

[ERROR]
Traceback (most recent call last):
  File "/twisted/test/test_reflect.py", line 202, in test_accumulateBases
    (Version("Twisted", 11, 0, 0), "inspect.getmro"),
exceptions.NameError: global name 'Version' is not defined

twisted.test.test_reflect.DeprecationTestCase.test_accumulateBases
===============================================================================

Reopens: #6689


git-svn-id: svn://svn.twistedmatrix.com/svn/Twisted/trunk@40034 bbbe8e31-12d6-0310-92fd-ac37d47ddeeb