Revert r43353 - test suite regression on Windows
Reopens: #7229

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "C:\Users\Build Slave\bot-glyph-6\windows7-64-py2.7-select\Twisted\twisted\internet\test\test_inotify.py", line 37, in setUp
    self.inotify = inotify.INotify()
exceptions.AttributeError: 'NoneType' object has no attribute 'INotify'

twisted.internet.test.test_inotify.TestINotify.test_deleteSelf
twisted.internet.test.test_inotify.TestINotify.test_ignoreFilePath
twisted.internet.test.test_inotify.TestINotify.test_seriesOfWatchAndIgnore
twisted.internet.test.test_inotify.TestINotify.test_simpleDeleteDirectory
-------------------------------------------------------------------------------


git-svn-id: svn://svn.twistedmatrix.com/svn/Twisted/trunk@43369 bbbe8e31-12d6-0310-92fd-ac37d47ddeeb