Revert r37124: LookupsTestCase.test_importExceptions failing on python 3.3
test_importExceptions is failing on Python 3.3 only because  a statement was
modified to clean up Python 2.3 code which introduced an issue in
test_reflectpy3.LookupsTestCase. This wasn't caught initially because the
buildslave for python 3.3 wass down.

======================================================================
FAIL: test_importExceptions (twisted.python.test.test_reflectpy3.LookupsTestCase)
test_importExceptions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "twisted/trial/_synctest.py", line 328, in assertRaises
    result = f(*args, **kwargs)
  File "twisted/python/_reflectpy3.py", line 273, in namedAny
    obj = getattr(obj, n)
AttributeError: 'module' object has no attribute 'reflect_helper_IE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "twisted/trial/_synctest.py", line 1185, in _run
    runWithWarningsSuppressed(suppress, method)
  File "twisted/python/util.py", line 1065, in runWithWarningsSuppressed
    return f(*args, **kwargs)
  File "twisted/python/test/test_reflectpy3.py", line 290, in test_importExceptions
    reflect.namedAny, "twisted.test.reflect_helper_IE")
  File "software/twisted/svn/Twisted/trunk/twisted/trial/_synctest.py", line 335, in assertRaises
    failure.Failure().getTraceback()))
twisted.trial.unittest.FailTest: <class 'AttributeError'> raised instead of ImportError:
 Traceback (most recent call last):
  File "twisted/trial/_synctest.py", line 1216, in _runFixturesAndTest
    if self._run(suppress, todo, method, result):
  File "twisted/trial/_synctest.py", line 1185, in _run
    runWithWarningsSuppressed(suppress, method)
  File "twisted/python/util.py", line 1065, in runWithWarningsSuppressed
    return f(*args, **kwargs)
  File "twisted/python/test/test_reflectpy3.py", line 290, in test_importExceptions
    reflect.namedAny, "twisted.test.reflect_helper_IE")
--- <exception caught here> ---
  File "twisted/trial/_synctest.py", line 328, in assertRaises
    result = f(*args, **kwargs)
  File "twisted/python/_reflectpy3.py", line 273, in namedAny
    obj = getattr(obj, n)
builtins.AttributeError: 'module' object has no attribute 'reflect_helper_IE'

Reopens: #5386
Refs: #6298


git-svn-id: svn://svn.twistedmatrix.com/svn/Twisted/trunk@37129 bbbe8e31-12d6-0310-92fd-ac37d47ddeeb